# サイト設定
title: "プログラミング言語 Nim (非公式日本語β版)"
description: >
  プログラミング言語 Nim は C, C++ と JavaScript へ
  コンパイルを行える簡潔で高速なプログラミング言語です。
baseurl: ""

nim_version: 1.0.4

defaults:
  -
    scope:
      path: ""
      type: pages
    values:
      layout: default
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post
      is_post: true
      title: "Nim Blog"

navigation:
  - title: ブログ
    url: /blog.html
  - title: 特徴
    url: /features.html
  - title: ダウンロード
    url: /install.html
  - title: 学ぶ
    url: /learn.html
  - title: 資料
    url: /documentation.html
  - title: フォーラム
    url: https://forum.nim-lang.org
  - title: 寄付
    url: /donate.html

# ビルド設定
markdown: kramdown
permalink: /blog/:year/:month/:day/:title.html
sass:
  style: compressed
exclude:
  - CNAME
  - README.md
  - LICENSE.md

gems:
  - jekyll-asciidoc

asciidoc: {}
asciidoctor:
  attributes:
    - imagesdir=/assets/news/images/asciidoc
    - icons=font
    - source-highlighter=pygments
    - pygments-css=style
